server:
  port: 8080
  servlet:
    context-path: /ShopmeAdmin
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopmedb
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
#logging:
#  file:
#    name: Shopme-backend.log
#  logback:
#    rollingpolicy:
#      file-name-pattern: Shopme-backend-%d{yyyy-MM-dd}.%i.log
#      max-file-size: 100KB
#      total-size-cap: 1MB
#      max-history: 14
#      clean-history-on-start: true